version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t your-docker-image-name .
      - run:
          name: Authenticate with AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - run:
          name: Push Docker image to ECR
          command: |
            docker tag your-docker-image-name:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/your-docker-image-name:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/your-docker-image-name:latest

  deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Deploy to AWS Elastic Beanstalk
          command: |
            eb init -p docker $EB_APP_NAME --region $AWS_REGION
            eb use $EB_ENV_NAME
            eb deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-push
      - deploy:
          requires:
            - build-and-push

#version: 2.1
#
#jobs:
#  build:
#    docker:
#      - image: circleci/python:3.9
#    environment:
#      DATABASE_URL: postgres://usermotionweb:passmotionweb@localhost:5432/basamotionweb
#
#
#    steps:
#      - checkout
#
#      - setup_remote_docker:
#          version: 20.10.7
#
#      - run:
#          name: Install dependencies
#          command: |
#            python -m pip install --upgrade pip
#            pip install -r requirements.txt
#
#      - run:
#          name: Run tests
#          command: |
#            python manage.py migrate
#            python manage.py test
#
#      - run:
#          name: Build Docker image
#          command: docker build -t myapp .
#
#  deploy:
#    docker:
#      - image: circleci/python:3.9
#
#    steps:
#      - checkout
#
#      - setup_remote_docker:
#          version: 20.10.7
#
#      - run:
#          name: Build Docker image
#          command: docker build -t myapp .
#
#      - run:
#          name: Deploy to AWS Elastic Beanstalk
#          command: |
#            sudo apt-get update
#            sudo apt-get install -y python3-pip
#            pip3 install awsebcli
#            eb init -p docker my-app --region $AWS_REGION
#            eb create my-app-env
#            eb deploy
#
#workflows:
#  version: 2
#  build_and_deploy:
#    jobs:
#      - build
#      - deploy:
#          requires:
#            - build
